name: text_recognition_flutter
description: A sample Flutter project that use text recognition.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  camera: ^0.10.0+4
  flutter:
    sdk: flutter
  google_mlkit_text_recognition: ^0.4.0
  permission_handler: ^10.2.0
  share_plus: ^7.0.0
  pdf: ^3.10.7
  path_provider: ^2.1.2
  google_mlkit_translation: ^0.5.0
  translator: ^1.0.3+1
  flutter_tts: ^4.2.1
  image_picker: ^1.1.2
  edge_detection: ^1.1.3
  image: ^4.3.0
  open_file: ^3.5.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true